object Versions {
    const val coreKtx = "1.9.0"
    const val appcompat = "1.6.1"
    const val material = "1.5.1"
    const val lifecycleRuntimeKtx = "2.6.1"
    const val activityCompose = "1.7.2"
    const val compose = "2023.05.01"
    const val navigationCompose = "2.8.1"
    const val lifecycleViewModelKtx = "2.7.0"
    const val hilt = "2.48"
    const val hiltCompiler = "1.0.0-alpha01"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "5.0.0-alpha.2"
    const val coroutines = "1.7.3"
    const val materialIcon = "1.0.0"
    const val contrainslayout = "1.0.1"
    const val MPAndroidChart = "3.1.0"
}